### ISSUE TITLE
Add support to Poke Balls

### ISSUE THREAD

**Issue by Jecvay** [DivineGenesis/BetterSoulBinding#11]
[Pixelmon Pokeball](https://pixelmonmod.com/wiki/index.php?title=Items#Pok.C3.A9_Balls)

when use the pokeball and pick it back, the binding disapeared

**Comment by DrZoddiak** [comment]
Could I get a bit more information on your setup?
Pixelmon version:
SpongeForge Version:
SoulBinding version:

Once I have that information I can attempt to replicate and fix.

**Comment by Jecvay** [comment]
Pixelmon Reforged Version 1.12.2-7.0.1
SpongeForge 1.12.2-7.1.5
SoulBinding 0.10.3
---

Because the poke ball object will be deleted after using(throw) it, and regen a new one when pick it back, so the binding will loss.

Just like the bow and arrow

**Comment by Rasgnarok** [comment]
Basically, pokeballs are spawned entities. What are you trying to do by binding it?

**Comment by Jecvay** [comment]
> Basically, pokeballs are spawned entities. What are you trying to do by binding it?

old players in my server give their pokeballs to new player
this will make new player lose the fun of earning it.

**Comment by DrZoddiak** [comment]
I can look more into this, but I don't have particularly high hopes.

I would assume the data would have to be saved by Pixelmon, and I cannot expect them to do that since they have no need for it.

Regardless if there _is_ something I can do without getting immensely hacky with it. I will attempt to do so.

**Comment by Jecvay** [comment]
is there any Event listen to [item insert to my inventory]
i think this is a good way, this can also be effected when OP use /give command to give someone an item, or he pick an item from chest to his inventory.

**Comment by DrZoddiak** [comment]
So the problem with that idea:
If you toss a pokeball with your binding on it, it loses it in the process.

So even if I have a binding set any time it goes in your inventory, you can still trade pokeballs by throwing them (because their already lost)

**Comment by Jecvay** [comment]
oh yes. what a pity.

**Comment by DrZoddiak** [comment]
I'm still going to _try_ and implement that as a feature though. I think it's nice for people who might want an all around binding.

**Comment by Jecvay** [comment]
As in Pixelmon's config, we can disable toss pokeball when not in the battle mode.
so listen to [item insert to my inventory] is still a nice thing.

**Comment by DrZoddiak** [comment]
Coming soon will be binding when someone interacts with an item in an inventory.
i.e User opens chest and grabs a bone (bone is in config list), and bone will be bound

Pickup already exists, and I also will be supporting binding from kits, this should cover all-around binding for the most part exempting #12 which shall remain open until I fix that.

I'll be closing this issue since it will be more or less resolved by next release
